#!/usr/bin/env python3
"""
Complete Report Generation Test
Tests the full workflow: login -> create case -> upload evidence -> generate report
"""
import requests
import json
import os
import time

BASE_URL = "http://127.0.0.1:8000/api"
USERNAME = "testlocal"
PASSWORD = "TestPass123!"

def login():
    """Get authentication token"""
    response = requests.post(f"{BASE_URL}/auth/login/", json={
        "username": USERNAME,
        "password": PASSWORD
    })
    if response.status_code == 200:
        token = response.json()['access']
        print(f"✅ Login successful")
        return token
    else:
        print(f"❌ Login failed: {response.text}")
        return None

def create_case(token):
    """Create a new test case"""
    headers = {"Authorization": f"Bearer {token}"}
    response = requests.post(f"{BASE_URL}/cases/", 
        json={
            "name": "Comprehensive Report Test",
            "description": "Testing AI-powered LaTeX report generation with detailed event analysis",
            "status": "OPEN"
        },
        headers=headers
    )
    if response.status_code == 201:
        case_id = response.json()['id']
        print(f"✅ Case created (ID: {case_id})")
        return case_id
    else:
        print(f"❌ Case creation failed: {response.text}")
        return None

def upload_evidence(token, case_id):
    """Upload sample evidence file"""
    headers = {"Authorization": f"Bearer {token}"}
    
    # Use the sample data file
    file_path = "/home/honours/YOUR_LOGS_CHECKER/sample_data/security_logs_sample.csv"
    
    if not os.path.exists(file_path):
        print(f"❌ Sample file not found: {file_path}")
        return None
    
    with open(file_path, 'rb') as f:
        files = {'file': ('security_logs_sample.csv', f, 'text/csv')}
        data = {'case': case_id}
        
        response = requests.post(f"{BASE_URL}/evidence/",
            headers=headers,
            data=data,
            files=files
        )
    
    if response.status_code == 201:
        evidence_id = response.json()['id']
        parsed_count = response.json().get('parsed_events_count', 0)
        print(f"✅ Evidence uploaded (ID: {evidence_id}, {parsed_count} events parsed)")
        return evidence_id
    else:
        print(f"❌ Evidence upload failed: {response.status_code} - {response.text}")
        return None

def check_events(token, case_id):
    """Check how many events were scored"""
    headers = {"Authorization": f"Bearer {token}"}
    
    # Get scored events - returns list directly
    response = requests.get(f"{BASE_URL}/scored-events/", headers=headers)
    if response.status_code == 200:
        data = response.json()
        # Handle both list and paginated response
        if isinstance(data, dict) and 'results' in data:
            all_events = data['results']
        elif isinstance(data, list):
            all_events = data
        else:
            all_events = []
        
        print(f"✅ Found {len(all_events)} total scored events")
        
        # Show risk distribution
        risk_counts = {}
        for event in all_events:
            risk = event.get('risk_label', 'UNKNOWN')
            risk_counts[risk] = risk_counts.get(risk, 0) + 1
        
        if risk_counts:
            print("   Risk Distribution:")
            for risk, count in sorted(risk_counts.items()):
                print(f"     {risk}: {count}")
        
        return len(all_events)
    else:
        print(f"❌ Failed to check events: {response.text}")
        return 0

def check_case_stats(token, case_id):
    """Check case statistics"""
    headers = {"Authorization": f"Bearer {token}"}
    
    response = requests.get(
        f"{BASE_URL}/cases/{case_id}/",
        headers=headers
    )
    
    if response.status_code == 200:
        result = response.json()
        print(f"✅ Case stats: {result.get('evidence_count', 0)} evidence files")
        return True
    else:
        print(f"⚠️  Case stats response: {response.status_code}")
        return False

def preview_latex(token, case_id):
    """Generate LaTeX preview"""
    headers = {"Authorization": f"Bearer {token}"}
    
    response = requests.post(
        f"{BASE_URL}/report/preview_latex/",
        headers=headers,
        json={"case_id": case_id}
    )
    
    if response.status_code == 200:
        data = response.json()
        latex_source = data.get('latex_source', '')
        
        print(f"✅ LaTeX preview generated ({len(latex_source)} characters)")
        
        # Check for AI content
        has_executive_summary = "Executive Summary" in latex_source
        has_ai_summary = "Analysis generated by:" in latex_source
        has_gemini = "Gemini" in latex_source
        has_risk_assessment = "Risk Assessment" in latex_source
        has_recommendations = "Recommendations" in latex_source
        has_events = "Events Analyzed" in latex_source
        
        print("\n📊 Report Content Check:")
        print(f"   Executive Summary: {'✅' if has_executive_summary else '❌'}")
        print(f"   AI-Generated Content: {'✅' if has_ai_summary else '❌'}")
        print(f"   Gemini Integration: {'✅' if has_gemini else '❌'}")
        print(f"   Risk Assessment: {'✅' if has_risk_assessment else '❌'}")
        print(f"   Recommendations: {'✅' if has_recommendations else '❌'}")
        print(f"   Events Analyzed: {'✅' if has_events else '❌'}")
        
        # Extract event count from LaTeX
        import re
        event_match = re.search(r'Events Analyzed.*?&\s*(\d+)', latex_source)
        if event_match:
            event_count = event_match.group(1)
            print(f"\n   📈 Events in Report: {event_count}")
            if event_count == "0":
                print("   ⚠️  WARNING: Report shows 0 events!")
        
        # Save LaTeX to file for inspection
        output_file = "/home/honours/YOUR_LOGS_CHECKER/test_report.tex"
        with open(output_file, 'w') as f:
            f.write(latex_source)
        print(f"\n💾 LaTeX saved to: {output_file}")
        
        return latex_source
    else:
        print(f"❌ LaTeX preview failed: {response.status_code} - {response.text}")
        return None

def compile_pdf(token, case_id, latex_source):
    """Compile LaTeX to PDF"""
    headers = {"Authorization": f"Bearer {token}"}
    
    response = requests.post(
        f"{BASE_URL}/report/compile_custom_latex/",
        headers=headers,
        json={
            "case_id": case_id,
            "latex_source": latex_source
        }
    )
    
    if response.status_code == 200:
        pdf_file = response.json().get('pdf_file')
        if pdf_file:
            print(f"✅ PDF compiled successfully: {pdf_file}")
            return pdf_file
        else:
            tex_file = response.json().get('tex_file')
            print(f"⚠️  PDF compilation unavailable, .tex file generated: {tex_file}")
            return tex_file
    else:
        print(f"❌ PDF compilation failed: {response.status_code} - {response.text}")
        return None

def main():
    print("=" * 60)
    print("🚀 COMPREHENSIVE REPORT GENERATION TEST")
    print("=" * 60)
    
    # Step 1: Login
    print("\n[1/7] Authenticating...")
    token = login()
    if not token:
        return
    
    # Step 2: Create case
    print("\n[2/7] Creating test case...")
    case_id = create_case(token)
    if not case_id:
        return
    
    # Step 3: Upload evidence
    print("\n[3/7] Uploading evidence file...")
    evidence_id = upload_evidence(token, case_id)
    if not evidence_id:
        return
    
    # Wait for parsing and scoring (happens automatically)
    print("\n⏳ Waiting 5 seconds for parsing and scoring to complete...")
    time.sleep(5)
    
    # Step 4: Check case stats
    print("\n[4/7] Checking case statistics...")
    check_case_stats(token, case_id)
    
    # Step 5: Check events
    print("\n[5/7] Checking scored events...")
    event_count = check_events(token, case_id)
    if event_count == 0:
        print("⚠️  No scored events found! Report may be empty.")
    
    # Step 6: Generate LaTeX preview
    print("\n[6/7] Generating LaTeX preview...")
    latex_source = preview_latex(token, case_id)
    if not latex_source:
        return
    
    # Step 7: Compile to PDF
    print("\n[7/7] Compiling to PDF...")
    pdf_file = compile_pdf(token, case_id, latex_source)
    
    print("\n" + "=" * 60)
    print("🎉 TEST COMPLETE!")
    print("=" * 60)
    print(f"\nCase ID: {case_id}")
    print(f"Evidence ID: {evidence_id}")
    print(f"Scored Events: {event_count}")
    print(f"LaTeX File: /home/honours/YOUR_LOGS_CHECKER/test_report.tex")
    if pdf_file:
        print(f"Output File: {pdf_file}")
    print("\n✨ Review the generated report for quality and completeness.")

if __name__ == "__main__":
    main()
