"""
PDF Report Generation Service
Generates court-ready forensic reports with chain of custody
"""
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib import colors
from datetime import datetime
from typing import Dict, List
import io


class ReportGenerator:
    """
    Generates PDF forensic reports
    Includes: chain of custody, timeline, event table, story narrative
    """
    
    def generate_pdf_report(self, case_data: Dict, output_path: str = None) -> bytes:
        """
        Generate PDF report
        
        Args:
            case_data: Dict containing case, evidence, events, stories
            output_path: Optional file path to save PDF
            
        Returns:
            PDF as bytes
        """
        # Create PDF buffer
        if output_path:
            buffer = output_path
        else:
            buffer = io.BytesIO()
        
        # Create document
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=inch,
            leftMargin=inch,
            topMargin=inch,
            bottomMargin=inch,
        )
        
        # Build content
        story = []
        styles = getSampleStyleSheet()
        
        # Title page
        story.extend(self._build_title_page(case_data, styles))
        story.append(PageBreak())
        
        # Chain of custody
        story.extend(self._build_chain_of_custody(case_data, styles))
        story.append(PageBreak())
        
        # Executive summary (story narratives)
        story.extend(self._build_executive_summary(case_data, styles))
        story.append(PageBreak())
        
        # Detailed timeline
        story.extend(self._build_timeline(case_data, styles))
        story.append(PageBreak())
        
        # Event evidence table
        story.extend(self._build_evidence_table(case_data, styles))
        
        # Build PDF
        doc.build(story)
        
        if isinstance(buffer, io.BytesIO):
            return buffer.getvalue()
        
        return None
    
    def _build_title_page(self, case_data: Dict, styles) -> List:
        """Build title page"""
        elements = []
        
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Title'],
            fontSize=24,
            textColor=colors.HexColor('#1a1a1a'),
            spaceAfter=30,
        )
        
        elements.append(Spacer(1, 2*inch))
        elements.append(Paragraph("FORENSIC LOG ANALYSIS REPORT", title_style))
        elements.append(Spacer(1, 0.5*inch))
        
        case_info = [
            f"<b>Case:</b> {case_data['case']['name']}",
            f"<b>Status:</b> {case_data['case']['status']}",
            f"<b>Generated:</b> {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"<b>Generated By:</b> {case_data['case']['created_by']}",
        ]
        
        for info in case_info:
            elements.append(Paragraph(info, styles['Normal']))
            elements.append(Spacer(1, 0.2*inch))
        
        return elements
    
    def _build_chain_of_custody(self, case_data: Dict, styles) -> List:
        """Build chain of custody section"""
        elements = []
        
        elements.append(Paragraph("CHAIN OF CUSTODY", styles['Heading1']))
        elements.append(Spacer(1, 0.2*inch))
        
        elements.append(Paragraph(
            "All evidence files have been cryptographically hashed (SHA-256) to ensure integrity.",
            styles['Normal']
        ))
        elements.append(Spacer(1, 0.2*inch))
        
        # Evidence table
        evidence_data = [['Filename', 'SHA-256 Hash', 'Upload Time', 'Uploader']]
        
        for evidence in case_data['evidence_files']:
            evidence_data.append([
                evidence['filename'],
                evidence['file_hash'][:16] + '...',
                evidence['uploaded_at'],
                evidence['uploaded_by'],
            ])
        
        table = Table(evidence_data, colWidths=[2*inch, 2*inch, 1.5*inch, 1.5*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        
        elements.append(table)
        
        return elements
    
    def _build_executive_summary(self, case_data: Dict, styles) -> List:
        """Build executive summary with story narratives"""
        elements = []
        
        elements.append(Paragraph("EXECUTIVE SUMMARY", styles['Heading1']))
        elements.append(Spacer(1, 0.2*inch))
        
        for story in case_data.get('stories', []):
            elements.append(Paragraph(f"<b>{story['title']}</b>", styles['Heading2']))
            elements.append(Paragraph(f"<i>Attack Phase: {story['attack_phase']}</i>", styles['Normal']))
            elements.append(Spacer(1, 0.1*inch))
            elements.append(Paragraph(story['narrative'], styles['Normal']))
            elements.append(Spacer(1, 0.3*inch))
        
        return elements
    
    def _build_timeline(self, case_data: Dict, styles) -> List:
        """Build event timeline"""
        elements = []
        
        elements.append(Paragraph("TIMELINE OF EVENTS", styles['Heading1']))
        elements.append(Spacer(1, 0.2*inch))
        
        for event in case_data.get('scored_events', [])[:50]:  # Limit to 50
            time_str = event['timestamp'].strftime('%Y-%m-%d %H:%M:%S')
            risk = event['risk_label']
            
            elements.append(Paragraph(
                f"<b>[{time_str}]</b> {event['event_type']} - <i>{risk}</i>",
                styles['Normal']
            ))
            elements.append(Paragraph(
                f"{event.get('inference_text', 'No explanation available')}",
                styles['Normal']
            ))
            elements.append(Spacer(1, 0.1*inch))
        
        return elements
    
    def _build_evidence_table(self, case_data: Dict, styles) -> List:
        """Build detailed evidence table"""
        elements = []
        
        elements.append(Paragraph("DETAILED EVIDENCE", styles['Heading1']))
        elements.append(Spacer(1, 0.2*inch))
        
        table_data = [['Time', 'Event Type', 'Confidence', 'Risk', 'Details']]
        
        for event in case_data.get('scored_events', [])[:100]:  # Limit to 100
            table_data.append([
                event['timestamp'].strftime('%m/%d %H:%M'),
                event['event_type'][:20],
                f"{event['confidence']:.2f}",
                event['risk_label'],
                event['raw_message'][:50] + '...',
            ])
        
        table = Table(table_data, colWidths=[1.2*inch, 1.5*inch, 0.8*inch, 0.8*inch, 2.5*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ]))
        
        elements.append(table)
        
        return elements


# Singleton instance
report_generator = ReportGenerator()
