import React from 'react';
import { useParams } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { apiClient } from '../api/client';
import type { StoryPattern } from '../types';

const StoryView: React.FC = () => {
  const { caseId } = useParams<{ caseId: string }>();
  const queryClient = useQueryClient();

  const { data: stories, isLoading } = useQuery<StoryPattern[]>({
    queryKey: ['stories', caseId],
    queryFn: async () => {
      const response = await apiClient.getStories(Number(caseId));
      return response.data.results || response.data;
    },
  });

  const generateMutation = useMutation({
    mutationFn: () => apiClient.generateStory(Number(caseId)),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['stories', caseId] });
    },
  });

  const regenerateMutation = useMutation({
    mutationFn: (storyId: number) => apiClient.regenerateStory(storyId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['stories', caseId] });
    },
  });

  const getPhaseIcon = (phase: string) => {
    const icons: Record<string, string> = {
      INITIAL_ACCESS: '[>>]',
      PERSISTENCE: '[<<]',
      PRIVILEGE_ESCALATION: '[^^]',
      LATERAL_MOVEMENT: '[->]',
      EXECUTION: '[**]',
      EXFILTRATION: '[>>]',
    };
    return icons[phase] || '[??]';
  };

  return (
    <div className="px-4 sm:px-0 animate-fadeIn">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-3xl font-bold text-white font-mono">$ generate_narrative --llm=gemini</h1>
        <button
          onClick={() => generateMutation.mutate()}
          disabled={generateMutation.isPending}
          className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 font-mono"
        >
          {generateMutation.isPending ? '[...] Generating' : '[AI] Generate Story'}
        </button>
      </div>

      {isLoading ? (
        <div className="text-center py-12 text-gray-400">Loading stories...</div>
      ) : stories && stories.length > 0 ? (
        <div className="space-y-6">
          {stories.map((story) => (
            <div key={story.id} className="bg-gray-900 border border-gray-800 rounded-lg p-8">
              {/* Header */}
              <div className="flex items-start justify-between mb-6">
                <div className="flex items-center space-x-3">
                  <div className="text-3xl font-mono text-blue-500">{getPhaseIcon(story.attack_phase)}</div>
                  <div>
                    <h2 className="text-2xl font-bold text-white font-mono">
                      {story.title}
                    </h2>
                    <p className="text-sm text-gray-400 mt-1">
                      {story.attack_phase.replace('_', ' ')} • Average Confidence:{' '}
                      {(story.avg_confidence * 100).toFixed(0)}%
                    </p>
                  </div>
                </div>
                <button
                  onClick={() => regenerateMutation.mutate(story.id)}
                  disabled={regenerateMutation.isPending}
                  className="px-3 py-1 text-sm border border-gray-600 text-gray-300 rounded-md hover:bg-gray-800 disabled:opacity-50 font-mono"
                >
                  [&lt;&gt;] Regenerate
                </button>
              </div>

              {/* Timeline Badge */}
              <div className="flex items-center space-x-4 mb-6 text-sm text-gray-400">
                <div>
                  <span className="font-medium">Start:</span>{' '}
                  {new Date(story.time_span_start).toLocaleString()}
                </div>
                <div>→</div>
                <div>
                  <span className="font-medium">End:</span>{' '}
                  {new Date(story.time_span_end).toLocaleString()}
                </div>
                <div className="ml-auto">
                  <span className="font-medium">{story.event_count}</span> events
                </div>
              </div>

              {/* Narrative */}
              <div className="prose prose-lg max-w-none">
                <div className="bg-black border border-gray-800 rounded-lg p-6 border-l-4 border-l-blue-600">
                  <p className="text-gray-300 leading-relaxed whitespace-pre-line">
                    {story.narrative_text}
                  </p>
                </div>
              </div>

              {/* Metadata */}
              <div className="mt-6 pt-6 border-t border-gray-800 text-xs text-gray-500">
                Generated by {story.generated_by_model} on{' '}
                {new Date(story.generated_at).toLocaleString()}
                {story.regenerated_count > 0 && (
                  <span> • Regenerated {story.regenerated_count} times</span>
                )}
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="bg-gray-900 border border-gray-800 rounded-lg p-12 text-center">
          <div className="text-6xl mb-4 font-mono text-gray-600">[NULL]</div>
          <h2 className="text-xl font-semibold text-white mb-2 font-mono">
            No Stories Generated Yet
          </h2>
          <p className="text-gray-400 mb-6">
            Click "Generate Story" to create an attack narrative from your evidence
          </p>
          <button
            onClick={() => generateMutation.mutate()}
            disabled={generateMutation.isPending}
            className="px-6 py-3 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 font-mono"
          >
            {generateMutation.isPending ? '[...] Generating' : '[AI] Generate Story'}
          </button>
        </div>
      )}
    </div>
  );
};

export default StoryView;
