# Generated by Django 6.0.1 on 2026-01-12 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='evidence/%Y/%m/%d/')),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('file_size', models.BigIntegerField()),
                ('log_type', models.CharField(choices=[('CSV', 'CSV'), ('SYSLOG', 'Syslog'), ('EVTX', 'Windows Event Log'), ('JSON', 'JSON'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_parsed', models.BooleanField(default=False)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('parse_error', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='core.case')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('user', models.CharField(blank=True, db_index=True, max_length=255)),
                ('host', models.CharField(blank=True, db_index=True, max_length=255)),
                ('event_type', models.CharField(db_index=True, max_length=255)),
                ('raw_message', models.TextField()),
                ('line_number', models.IntegerField()),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_events', to='core.evidencefile')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('JSON', 'JSON')], max_length=10)),
                ('file', models.FileField(upload_to='reports/%Y/%m/%d/')),
                ('file_hash', models.CharField(max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.case')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoredEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(db_index=True)),
                ('risk_label', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=20)),
                ('feature_scores', models.JSONField(default=dict)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('inference_text', models.TextField(blank=True)),
                ('inference_generated_at', models.DateTimeField(blank=True, null=True)),
                ('inference_model', models.CharField(blank=True, max_length=50)),
                ('manual_explanation', models.TextField(blank=True)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scored', to='core.parsedevent')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence', 'parsed_event__timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.case')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('scored_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.scoredevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('narrative_text', models.TextField()),
                ('attack_phase', models.CharField(choices=[('INITIAL_ACCESS', 'Initial Access'), ('PERSISTENCE', 'Persistence'), ('PRIVILEGE_ESCALATION', 'Privilege Escalation'), ('LATERAL_MOVEMENT', 'Lateral Movement'), ('EXECUTION', 'Execution'), ('EXFILTRATION', 'Data Exfiltration'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('avg_confidence', models.FloatField()),
                ('event_count', models.IntegerField()),
                ('time_span_start', models.DateTimeField()),
                ('time_span_end', models.DateTimeField()),
                ('generated_by_model', models.CharField(max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('regenerated_count', models.IntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_patterns', to='core.case')),
                ('scored_events', models.ManyToManyField(related_name='story_patterns', to='core.scoredevent')),
            ],
            options={
                'ordering': ['-avg_confidence', 'time_span_start'],
            },
        ),
        migrations.AddIndex(
            model_name='evidencefile',
            index=models.Index(fields=['file_hash'], name='core_eviden_file_ha_a6f384_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencefile',
            index=models.Index(fields=['case', 'uploaded_at'], name='core_eviden_case_id_8c486e_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedevent',
            index=models.Index(fields=['evidence_file', 'timestamp'], name='core_parsed_evidenc_206e55_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='core_parsed_event_t_4c3734_idx'),
        ),
        migrations.AddIndex(
            model_name='scoredevent',
            index=models.Index(fields=['confidence', 'is_archived'], name='core_scored_confide_037fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='scoredevent',
            index=models.Index(fields=['risk_label', 'is_archived'], name='core_scored_risk_la_b81918_idx'),
        ),
    ]
