# Generated by Django 6.0.1 on 2026-01-13 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencefile',
            name='file_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='evidencefile',
            constraint=models.UniqueConstraint(fields=('case', 'file_hash'), name='unique_file_per_case'),
        ),
    ]
