# Generated by Django 6.0.1 on 2026-01-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_evidencefile_file_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('PDF', 'PDF'), ('PDF_LATEX', 'LaTeX PDF'), ('CSV', 'CSV'), ('JSON', 'JSON')], max_length=20),
        ),
    ]
