# Generated by Django 5.2.10 on 2026-02-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_report_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedevent',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
